name = "proxy"
main = "src/index.ts"
compatibility_date = "2023-11-09"

[vars]
BACKEND_RENDER_URL = "https://cella-backend.onrender.com"
FRONTEND_RENDER_URL = "https://cella-frontend.onrender.com"
TUS_RENDER_URL = "https://cella-tus.onrender.com"
ELECTRIC_RENDER_URL = "https://cella-electric-sync-service.onrender.com"

workers_dev = false

routes = [
  { pattern = "cellajs.com/*", zone_name = "cellajs.com", custom_domain = true },
  { pattern = "www.cellajs.com/*", zone_name = "cellajs.com", custom_domain = true }
]